# Generated by Django 6.0.3 on 2026-03-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=200)),
                ('block', models.CharField(max_length=200)),
                ('gram_panchayat', models.CharField(max_length=200)),
                ('ward', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=200)),
                ('polling_station', models.CharField(max_length=200)),
                ('polling_booth', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('voter_id', models.CharField(max_length=20, unique=True)),
                ('name_hindi', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voters.location')),
            ],
            options={
                'indexes': [models.Index(fields=['name_hindi'], name='voters_vote_name_hi_7249b8_idx')],
            },
        ),
    ]
